class CfgPatches {
	class WW2_SPE_Structures_c {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {
			"A3_Structures_F"
		};
	};
};

#define ORIGAMI_CLASS(PATH,MODELNAME) \
class land_##MODELNAME : House_F { \
    scope = 1; \
    model = \WW2\SPE_Structures\##PATH##MODELNAME##.p3d; \
}

class CfgVehicles {
	class House_F;

    ORIGAMI_CLASS(Civilian\Church\,SPE_Addon_Roof_01_v1);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_Bell);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_BellTower_01);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_BellTower_02);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_BellTower_03);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_DoubleDoor);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_Front);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_Hallway);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_Rear_01);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_Rear_02);
    ORIGAMI_CLASS(Civilian\Church\,SPE_Church_SingleDoor);
    ORIGAMI_CLASS(Civilian\Dominants\,SPE_Townhall);
    ORIGAMI_CLASS(Civilian\Dominants\,SPE_Chateau_01);
    ORIGAMI_CLASS(Civilian\House\,SPE_Bunkhouse);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_01);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_01b);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_01c);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_02);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_03);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_04);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_05);
    ORIGAMI_CLASS(Civilian\House\,SPE_Corner_house_06);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Arch_01);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Arch_02);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Big_01);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Big_02);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Big_03);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Big_04);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Small_01);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Small_02);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Small_03);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Small_04);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Thatch_01);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Thatch_02);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Thatch_03);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Thatch_04);
    ORIGAMI_CLASS(Civilian\House\,SPE_House_Thatch_05);
    ORIGAMI_CLASS(Civilian\House\,SPE_Manor_House);

    ORIGAMI_CLASS(Commercial\Office\,SPE_Office_Small_01);
    ORIGAMI_CLASS(Commercial\Office\,SPE_Office_Small_02);
    ORIGAMI_CLASS(Commercial\Shops\,SPE_MarketStall_01);
    ORIGAMI_CLASS(Commercial\Shops\,SPE_MarketStall_02);
    ORIGAMI_CLASS(Commercial\Shops\,SPE_MarketStall_03);
    ORIGAMI_CLASS(Commercial\Shops\,SPE_Shop_01);
    ORIGAMI_CLASS(Commercial\Shops\,SPE_Shop_02);
    ORIGAMI_CLASS(Commercial\Shops\,SPE_Shop_03);
    ORIGAMI_CLASS(Commercial\Shops\,SPE_Shop_04);

    ORIGAMI_CLASS(Data\,SPE_invisiblepath_1m);
    ORIGAMI_CLASS(Data\,SPE_invisiblepath_3m);

    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Barn_01);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Barn_Thatch_01);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Barn_Thatch_02);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Farmhouse_01);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Haystack);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Haystack_destroyed_v1);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Haystack_destroyed_v2);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Haystack_low);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Straw_Bale);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Straw_Bale_Stack_01);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Straw_Bale_Stack_02);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_StrawStack_01_destroyed_v1);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_StrawStack_01_destroyed_v2);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Tractor_01);
    ORIGAMI_CLASS(Industrial\Agriculture\,SPE_Windmill);
    ORIGAMI_CLASS(Industrial\Construction\,SPE_Covered_Pallets_01);
    ORIGAMI_CLASS(Industrial\Construction\,SPE_Covered_Pallets_01_Grey);
    ORIGAMI_CLASS(Industrial\Construction\,SPE_Covered_Pallets_01_Olive);
    ORIGAMI_CLASS(Industrial\Construction\,SPE_Covered_Pallets_02);
    ORIGAMI_CLASS(Industrial\Construction\,SPE_Covered_Pallets_02_Navy);
    ORIGAMI_CLASS(Industrial\Construction\,SPE_Covered_Pallets_02_Olive);
    ORIGAMI_CLASS(Industrial\Construction\,SPE_Pallet);

    ORIGAMI_CLASS(Infrastructure\Bridge\,SPE_Bridge_Stone_01);
    ORIGAMI_CLASS(Infrastructure\Bridge\,SPE_Bridge_Stone_01_Down);
    ORIGAMI_CLASS(Infrastructure\Bridge\,SPE_Bridge_Stone_01_Up);
    ORIGAMI_CLASS(Infrastructure\Bridge\,SPE_Bridge_Wood_01);
    ORIGAMI_CLASS(Infrastructure\Bridge\,SPE_Bridge_Wood_02);
    ORIGAMI_CLASS(Infrastructure\Water_tower\,SPE_water_tower_01);
    ORIGAMI_CLASS(Infrastructure\Water_tower\,SPE_water_tower_01_camo);
    ORIGAMI_CLASS(Infrastructure\,SPE_Carriage_Box);
    ORIGAMI_CLASS(Infrastructure\,SPE_Carriage_Tanker);
    ORIGAMI_CLASS(Infrastructure\,SPE_Carriage_Flat);
    ORIGAMI_CLASS(Infrastructure\,SPE_Mud_Decal);
    ORIGAMI_CLASS(Infrastructure\,SPE_StreetLamp);
    ORIGAMI_CLASS(Infrastructure\,SPE_StreetLamp_off);
    ORIGAMI_CLASS(Infrastructure\,SPE_StreetLamp_pole);
    ORIGAMI_CLASS(Infrastructure\,SPE_StreetLamp_pole_off);
    ORIGAMI_CLASS(Infrastructure\,SPE_StreetLamp_wall);
    ORIGAMI_CLASS(Infrastructure\,SPE_StreetLamp_wall_off);

    ORIGAMI_CLASS(Items\Agriculture\,SPE_Bale_Fork);
    ORIGAMI_CLASS(Items\Agriculture\,SPE_Milk_Bottle);
    ORIGAMI_CLASS(Items\Agriculture\,SPE_Milk_Can);
    ORIGAMI_CLASS(Items\Agriculture\,SPE_Milk_Crate);
    ORIGAMI_CLASS(Items\Agriculture\,SPE_Scarecrow);
    ORIGAMI_CLASS(Items\Agriculture\,SPE_Vegtable_Patch_Decal);
    ORIGAMI_CLASS(Items\Agriculture\,SPE_Wagon_01);
    ORIGAMI_CLASS(Items\Agriculture\,SPE_Wagon_02);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Bicycle_01);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Bottle_Shelf);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Bottle_Shelf_Empty);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Cider_Bottle_01);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Cider_Bottle_02);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Cider_Bottle_03);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Cider_Crate);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Cider_Crate_Empty);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_01_Blue);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_01_Green);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_01_White);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_02_Blue);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_02_Green);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_02_White);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_03_Blue);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_03_Green);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Doghouse_03_White);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Fountain);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Ladder);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Litter_Long);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Litter_Square3);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Litter_Square5);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Onion_Lamp);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Ger_Lamp);
    ORIGAMI_CLASS(Items\Civilian\,SPE_US_Lamp);
    ORIGAMI_CLASS(Items\Civilian\,SPE_Cabinet);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_01);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_01_Side);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_01_Small);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_02_Brown);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_02_Green);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_02_Open_Brown);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_02_Small_Brown);
    ORIGAMI_CLASS(Items\Commercial\,SPE_Wooden_Barrel_02_Small_Green);
    ORIGAMI_CLASS(Items\Cultural\,SPE_Church_Bench);
    ORIGAMI_CLASS(Items\Cultural\,SPE_Church_Calvary_Mary);
    ORIGAMI_CLASS(Items\Cultural\,SPE_Church_Effigy_Mary);

    ORIGAMI_CLASS(Military\Casemate\,SPE_58C);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H134);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H607);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H612);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H622);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H630);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H667);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H669);
    ORIGAMI_CLASS(Military\Casemate\,SPE_H679);
    ORIGAMI_CLASS(Military\Supplies\,SPE_57MM_shellcase_01);
    ORIGAMI_CLASS(Military\Supplies\,SPE_57MM_shellcase_02);
    ORIGAMI_CLASS(Military\Supplies\,SPE_57MM_shellcase_03);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_01);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_01_stack);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_02);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_02_Covered);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_02_stack);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_03);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_03_Covered);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_03_stack);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_04);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_04_Covered);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_04_stack);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_05);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammobox_German_05_stack);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammocan_German);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammocrate_US_01);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammocrate_US_02);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammocrate_US_03);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Ammocrate_US_04);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Artillery_Rounds_US);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Foodcrate_US_A);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Foodcrate_US_B);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Foodcrate_US_C);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Foodcrate_US_D);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Fuel_Barrel_German);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Fuel_Barrel_US);
    ORIGAMI_CLASS(Military\Supplies\,SPE_FuelCan_US);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Jerrycan);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Pak40Box_01);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Pak40Box_02);
    ORIGAMI_CLASS(Military\Supplies\,SPE_Pak40Tube);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_4m);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_8m);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_45_Ext);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_45_Int);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_90_Ext);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_90_Int);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_135_Ext);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Cnc_Trench_135_Int);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_3m);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_3m_sandbags);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_6m);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_6m_sandbags);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_6m45);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_6m45_sandbags);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_6m315);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_6m315_sandbags);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_Cover);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_Decal_01);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_Decal_02);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_Decal_03);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_Pile_01);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Dugout_Pile_02);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Slit_Trench_fence_long);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Slit_Trench_fence_short);
    ORIGAMI_CLASS(Military\Trenches\,SPE_Slit_Trench_support);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Single);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Short_Low);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Short);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Nest);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Long_Thick);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Long_Line);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Long);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Gun_Hole);
    ORIGAMI_CLASS(Military\Walls\,SPE_Sandbag_Curve);
    ORIGAMI_CLASS(Military\,SPE_BarbedWire_01);
    ORIGAMI_CLASS(Military\,SPE_BarbedWire_02);
    ORIGAMI_CLASS(Military\,SPE_BarbedWire_03);
    ORIGAMI_CLASS(Military\,SPE_BarbedWire_04);
    ORIGAMI_CLASS(Military\,SPE_BarbedWire_End);
    ORIGAMI_CLASS(Military\,SPE_BarbedWire_Posts);
    ORIGAMI_CLASS(Military\,SPE_Crater);
    ORIGAMI_CLASS(Military\,SPE_Crater_Decal_Large);
    ORIGAMI_CLASS(Military\,SPE_Crater_Decal_Small);
    ORIGAMI_CLASS(Military\,SPE_Element_c);
    ORIGAMI_CLASS(Military\,SPE_Element_c_rust);
    ORIGAMI_CLASS(Military\,SPE_German_Tent);
    ORIGAMI_CLASS(Military\,SPE_German_Tent_Oak);
    ORIGAMI_CLASS(Military\,SPE_Guardbox);
    ORIGAMI_CLASS(Military\,SPE_HedgeHog);
    ORIGAMI_CLASS(Military\,SPE_maintenanceCrane);
    ORIGAMI_CLASS(Military\,SPE_Netting_02);
    ORIGAMI_CLASS(Military\,SPE_Netting_01);
    ORIGAMI_CLASS(Military\,SPE_Stretcher);
    ORIGAMI_CLASS(Military\,SPE_Tent_01);
    ORIGAMI_CLASS(Military\,SPE_Tent_02);
    ORIGAMI_CLASS(Military\,SPE_Tent_03);
    ORIGAMI_CLASS(Military\,SPE_US_Tent);

    ORIGAMI_CLASS(Ruins\,SPE_Barn_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Bunkhouse_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_01b_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_01c_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_02_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_03_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_04_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_05_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Corner_house_06_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Farmhouse_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Arch_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Arch_02_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Big_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Big_02_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Big_03_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Big_04_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Small_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Small_02_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Small_03_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Small_04_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Thatch_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Thatch_02_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Thatch_03_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Thatch_04_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_House_Thatch_05_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Manor_House_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Office_Small_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Office_Small_02_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Shop_01_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Shop_02_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Shop_03_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Shop_04_ruins);
    ORIGAMI_CLASS(Ruins\,SPE_Townhall_ruins);

    ORIGAMI_CLASS(SPE_A3_Agriculture\,SPE_A3_barn_01_brown);
    ORIGAMI_CLASS(SPE_A3_Agriculture\,SPE_A3_barn_01_grey);

    ORIGAMI_CLASS(SPE_A3_Camps\,SPE_A3_caravan_01_green);

    ORIGAMI_CLASS(SPE_A3_Cultural\,SPE_A3_church_04_lightblue_damaged);
    ORIGAMI_CLASS(SPE_A3_Cultural\,SPE_A3_church_04_white_damaged);
    ORIGAMI_CLASS(SPE_A3_Cultural\,SPE_A3_church_04_white_red_damaged);
    ORIGAMI_CLASS(SPE_A3_Cultural\,SPE_A3_church_04_yellow_damaged);

    ORIGAMI_CLASS(SPE_A3_Props_exp\,SPE_A3_Bulldozer_01_wreck_green_US);

    ORIGAMI_CLASS(SPE_A3_Walls\,SPE_A3_stonewall_01_s_10m);
    ORIGAMI_CLASS(SPE_A3_Walls\,SPE_A3_stonewall_01_s_d);

    ORIGAMI_CLASS(Walls\Gates\,SPE_Wood_Gate_4m_01);
    ORIGAMI_CLASS(Walls\Gates\,SPE_Wood_Gate_4m_02);
    ORIGAMI_CLASS(Walls\Gates\,SPE_Wood_Gate_5m_01);
    ORIGAMI_CLASS(Walls\Gates\,SPE_Wood_Gate_5m_02);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Gate_01_Blue);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Gate_01_Green);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Gate_01_White);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Pillar_01_Ruin);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Pillar_01_Small);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Pillar_01_Tall);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Pillar_02_Tall);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Gate);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Short);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Short_d);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Short_End);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Tall);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_01_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Gate);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Short);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Short_d);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Short_End);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Tall);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_02_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Gate);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Short);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Short_d);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Short_End);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Tall);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_03_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French\,SPE_French_Wall_Ruin);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Pillar_Dark_01_Ruin);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Pillar_Dark_01_Small);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Pillar_Dark_01_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Pillar_Dark_02_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Gate);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Small);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Small_d);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Small_End);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_01_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Gate);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Small);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Small_d);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Small_End);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_02_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Gate);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Small);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Small_d);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Small_End);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French Dark\,SPE_French_Wall_Dark_03_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Pillar_Light_01_Ruin);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Pillar_Light_01_Small);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Pillar_Light_01_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Pillar_Light_02_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Gate);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Small);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Small_d);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Small_End);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_01_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Gate);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Small);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Small_d);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Small_End);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_02_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Gate);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Small);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Small_d);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Small_End);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Tall);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Tall_d);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Tall_dam);
    ORIGAMI_CLASS(Walls\Stone\French Light\,SPE_French_Wall_Light_03_Tall_End);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_4m);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_4m_LC);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_8m);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_8m_LC);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_Dam_01);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_Dam_01_LC);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_Dam_02);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_Dam_02_LC);
    ORIGAMI_CLASS(Walls\Stone\Low Wall\,SPE_Stonewall_Low_Pillar);
    ORIGAMI_CLASS(Walls\Wood\,SPE_Wood_Fence_02_Gate);
    ORIGAMI_CLASS(Walls\Wood\,SPE_Wood_TrenchLogWall_01_4m_v1);
    ORIGAMI_CLASS(Walls\Wood\,SPE_Wood_TrenchLogWall_01_4m_v1_LC);
    ORIGAMI_CLASS(Walls\Wood\,SPE_Wood_TrenchLogWall_01_4m_v2);
    ORIGAMI_CLASS(Walls\Wood\,SPE_Wood_TrenchLogWall_01_4m_v2_LC);
    ORIGAMI_CLASS(Walls\Wood\,SPE_Wood_TrenchLogWall_01_4m_v3);
    ORIGAMI_CLASS(Walls\Wood\,SPE_Wood_TrenchLogWall_01_4m_v3_LC);
};
